"""empty message

Revision ID: 2c4d623174e1
Revises: 
Create Date: 2021-02-26 12:00:05.396077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4d623174e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('car', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_car_car'), 'user_car', ['car'], unique=True)
    op.create_index(op.f('ix_user_car_name'), 'user_car', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_car_name'), table_name='user_car')
    op.drop_index(op.f('ix_user_car_car'), table_name='user_car')
    op.drop_table('user_car')
    # ### end Alembic commands ###
