services:
  django:
    container_name: django_container
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/django_development
    command: 'gunicorn config.wsgi -b 0.0.0.0:${DJANGO_CONTAINER_PORT} -w 4'
    ports:
      - ${DJANGO_HOST_PORT}:${DJANGO_CONTAINER_PORT}
    volumes:
      - .:/code
    depends_on:
      - postgres
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECURE_SSL_REDIRECT: ${DJANGO_SECURE_SSL_REDIRECT}
      DJANGO_SECURE_HSTS_SECONDS: ${DJANGO_SECURE_HSTS_SECONDS}
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: ${DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS}
      DJANGO_SECURE_HSTS_PRELOAD: ${DJANGO_SECURE_HSTS_PRELOAD}
      DJANGO_SESSION_COOKIE_SECURE: ${DJANGO_SESSION_COOKIE_SECURE}
      DJANGO_CSRF_COOKIE_SECURE: ${DJANGO_CSRF_COOKIE_SECURE}
      DJANGO_HOSTS: ${DJANGO_HOSTS}
      DJANGO_DATABASE_NAME: ${DJANGO_DATABASE_NAME}
      DJANGO_DATABASE_USER: ${DJANGO_DATABASE_USER}
      DJANGO_DATABASE_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      DJANGO_DATABASE_HOST: ${DJANGO_DATABASE_HOST}
      DJANGO_DATABASE_PORT: ${DJANGO_DATABASE_PORT}
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}
volumes:
  postgres_data:
  pgadmin_data:
