services:
  django:
    container_name: django_container
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /code/django_development/manage.py runserver 0.0.0.0:8000'
    ports:
    - 8000:8000
    volumes:
    - .:/code
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: django_development_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  postgres_data:
  pgadmin_data: